server:
  port: 8083
spring:
  application:
    name: permission-service
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/de_demo_permission?useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: DEFAULT_GROUP
      namespace: ""
      username: nacos
      password: nacos
      application: seata-server
  tx-service-group: de-demo
  service:
    vgroup-mapping:
      de-demo: "default"

logging:
  file:
    path: D:/javaprojects/digital-engine-demo/permission-service/logs/

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml