server:
  port: 8082
spring:
  application:
    name: logging-service
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/de_demo_logging?useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 3
          stateless: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  file:
    path: D:/javaprojects/digital-engine-demo/logging-service/logs/