server:
  port: 8082
spring:
  application:
    name: logging-service
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/de_demo_logging?useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848