server:
  port: 8083
spring:
  application:
    name: permission-service
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/de_demo_permission?useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml