server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    password: root
    database: 5
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://comments-service
          predicates:
            - Path=/comments/**


jwt:
  secret: 121yguy
  exp: 604800

secure:
  auth:
    include-paths:
      - /users
      - /user/**
    exclude-paths:
      - /user/login
      - /user/register