server:
  port: 8081
spring:
  application:
    name: permission-service
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/de_demo_user?useSSL=false"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # shardingsphere配置由chatgpt生成
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/de_demo_user
        username: root
        password: root

    rules:
      sharding:
        tables:
          users:
            actual-data-nodes: ds.users_$->{0..2}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: user-id-hash-mod
            key-generate-strategy:
              column: user_id
              key-generator-name: snowflake

        sharding-algorithms:
          user-id-hash-mod:
            type: HASH_MOD
            props:
              sharding-count: 3

        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 1  # 不同节点设置不同

    props:
      sql-show: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml