server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/de_demo_user?useSSL=false&serverTimezone=Asia/Shanghai"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: root
    database: 5
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # shardingsphere配置部分由chatgpt生成
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/de_demo_user?useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root

    rules:
      sharding:
        tables:
          users:
            actual-data-nodes: ds.users_$->{0..2}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: user-id-hash-mod
            key-generate-strategy:
              column: user_id
              key-generator-name: snowflake

        sharding-algorithms:
          user-id-hash-mod:
            type: HASH_MOD
            props:
              sharding-count: 3

        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 1  # 不同节点设置不同

    props:
      proxy-transaction-type: SEATA
      transaction.seata.enabled: true
      proxy.transaction.enabled: true
      transaction_type: AT
      sql-show: false

seata:
  enabled: true
  enable-auto-data-source-proxy: false
  data-source-proxy-mode: AT
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: DEFAULT_GROUP
      namespace: ""
      username: nacos
      password: nacos
      application: seata-server
  tx-service-group: de-demo
  service:
    vgroup-mapping:
      de-demo: "default"

logging:
  file:
    path: D:/javaprojects/digital-engine-demo/user-service/logs/

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 121yguy
  exp: 604800

secret-keys:
  email-secret-key: 1234567890qwerty
  phone-secret-key: 67012938745